name: Build Pull Request

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive artifacts (Connect Bungee)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Connect Bungee
          path: bungee/build/libs/connect-bungee.jar

      - name: Archive artifacts (Connect Spigot)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Connect Spigot
          path: spigot/build/libs/connect-spigot.jar

      - name: Archive artifacts (Connect Velocity)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Connect Velocity
          path: velocity/build/libs/connect-velocity.jar